# ==================== 核心模型配置 ====================
# 默认使用 GPT-5 模型
model = "gpt-5"
model_provider = "openai"

# 推理配置
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
model_verbosity = "medium"
model_supports_reasoning_summaries = true

# 推理显示配置
hide_agent_reasoning = false
show_raw_agent_reasoning = true

# ==================== 批准与沙箱配置 ====================
# 从不提示批准（适合 CI/自动化）
approval_policy = "never"

# 完全访问权限（危险模式）
sandbox_mode = "danger-full-access"
windows_wsl_setup_acknowledged = true

# ==================== 工具配置 ====================
[tools]
web_search = true  # 启用网络搜索工具

# ==================== 沙箱网络配置 ====================
[sandbox_workspace_write]
network_access = true

# ==================== 模型配置文件 ====================
# 可通过 --profile 参数切换模型

[profiles.gpt5-high]
model = "gpt-5"
model_reasoning_effort = "high"
approval_policy = "never"

[profiles.gpt5-medium]
model = "gpt-5"
model_reasoning_effort = "medium"
approval_policy = "never"

[profiles.o3]
model = "o3"
model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
approval_policy = "never"

[profiles.o4-mini]
model = "o4-mini"
model_reasoning_effort = "medium"
model_reasoning_summary = "concise"
approval_policy = "never"

[profiles.gpt-4o]
model = "gpt-4o"
approval_policy = "never"

# ==================== 项目信任配置 ====================

[projects."/mnt/d/AI_Projects"]
trust_level = "trusted"

[projects.'\\?\D:\AI_Projects']
trust_level = "trusted"
