site:
  base_url: "https://immigration.gov.ph"
  services_path: "/services/"
paths:
  workspace_root: "D:/AI_Projects/TelegramChatHistory/Workspace/VBcombined/BI"
  env_file: "D:/AI_Projects/Kobe/.env"
  yaml_template: "service_yaml_template.yaml"
  md_template: "mdtemplate.md"
  price_doc: "BI_price.md"
  price_raw: "prices_raw.txt"
  price_temp: "pricetemp.md"
  rename_tmp: "../.rename_tmp"
  pdf_cache: "../.pdf_text_cache"
llm:
  convert_yaml:
    model: "gpt-5-2025-08-07"
    system_prompt: |-
      system_role: "STRUCTURE_CONVERTER_V2"
      description: >
        将业务说明文档（Markdown）转换为标准化 YAML（v2）。
        目的：为客服机器人提供“骨架+占位符”数据结构，便于本地脚本按键名拼接替换。
        绝不补写或推断。仅输出 YAML，无任何解释或注释。

      reference_template: |
        version: ""
        updated_at: ""
        default_language: "zh-CN"
        aliases: []
        department: ""
        name: ""
        slug: ""
        type: "reference"
        semantic_profile:
          intent_id: ""
          category: ""
          tags: []
        service_overview: ""
        applicability:
          items: {}
        preconditions:
          required: {}
          not_eligible: {}
        pre_required_documents:
          mandatory: {}
          conditional: {}
        process:
          steps: {}
          variants: {}
          notes: ""
        pricing:
          metadata:
            last_verified: ""
            source: ""
          items: {}
        deliverables:
          description: ""
          items: {}
        kpis:
          processing_time: ""
        risks:
          items: {}
        info_collection:
          applicant: {}
          spouse: {}
          father: {}
          mother: {}
          children: {}
          dependents: {}
          employment: {}
          authorization: {}
          arrival_info: {}
          travel_history: {}
          compliance: {}
          additional_details: {}
        acknowledgement_flags:
          data_privacy_consent: ""
          certification_statement: ""
        faq:
          qas: {}
        disclaimers:
          items: {}
        service_related:
          links: {}

      schema_rules:
        - 一级与二级键名必须与 reference_template 完全一致，顺序相同，不得新增/改名/重排。
        - 所有“容器”必须是 map（字典），并以第三级“动态ID”作为键；以下容器禁止使用数组：
          pricing.items, deliverables.items, process.steps, process.variants, risks.items,
          faq.qas, disclaimers.items, applicability.items, preconditions.required,
          preconditions.not_eligible, pre_required_documents.mandatory, service_related.links,
          info_collection.applicant/spouse/father/mother/children/dependents/employment/authorization/arrival_info/travel_history/compliance/additional_details。
        - 唯一允许的数组：
          aliases, semantic_profile.tags,
          pre_required_documents.conditional.{trigger-id}.documents（字符串数组）, 
          process.variants.{variant-id}.extra_requirements（字符串数组）。
        - pre_required_documents.conditional 为 map：
          { trigger-id: { trigger: "…", documents: [] } }。若没有任何条件触发，输出空 map {}。
        - 条目对象字段集合必须固定：
          pricing.items 采用“分组-明细-属性”三段式结构：
            pricing.items.{group-id} = { label, details, total? }
            其中：
              label: 分组的人类可读名称（如 "Top 1000 企业 · 主申请人 · 1年"）。
              details: map，键为 {detail-id}（如 visa-fee, acr-icard, visa-sticker, express-lane, lrf 等），值为 { amount, notes, attr }；
              total: 可选，对应分组汇总金额对象 { amount, notes, attr }（若无法精确汇总则 amount.value 置空）。
          deliverables.items.{id} = { name, usage }；
          process.steps.{id} = { order, title, description }；
          process.variants.{id} = { name, trigger, description, extra_requirements }；
          faq.qas.{id} = { question, answer }。
        - info_collection.* 下每个字段条目必须为“字段对象（field object）”，不可为纯字符串：
          info_collection.(applicant|spouse|father|mother|children|dependents|employment|authorization|arrival_info|travel_history|compliance|additional_details).{field-id}
            = { label, type, required, format, pattern, example, notes }
          说明：
            label: 字段的人类可读名称（中文）；
            type: 取值之一 [string, integer, number, boolean, date, datetime, enum]；
            required: 取值 [true, false]（字符串，非布尔）；
            format: 可选，细分格式（如 passport-no, iso-date, e164-phone, email, country-iso2）；
            pattern: 可选，正则；
            example: 可选，示例值（不含个人真实信息）；
            notes: 可选，补充说明。
        - 金额对象（amount）必须是对象而非字符串，且满足：
            基本字段：
              amount.currency: 三位大写货币（如 PHP、USD、EUR），类型 str；
              amount.value: 整数金额，若未知设为 null；
              amount.display: 保留原文格式（如 "PHP 10,630"），可空；
              amount.range（可选）：用于价格区间；
              amount.tiers（可选）：用于多档收费（如 LRF 不同档位）。
            notes 字段必须是字符串，说明适用条件或来源。
        - 若金额未知但需提示“以现场为准”之类表述，amount.value 设为 null，amount.display 设为 ""，notes 写明说明文字。
        - references 或对比性费用不得写入 pricing.items，只能在 notes 提示“另参照 XX 费用表”。
        - 缺失信息：字符串键写为 ""；容器键写为 {}；数组键写为 []。禁止省略键。
        - Map 插入顺序需遵循源文出现顺序（用于前端有序渲染）。
        - 禁止输出超出模板的任意键；禁止输出注释/Markdown/解释性文字。

      id_rules:
        - 第三级动态ID采用 kebab-case，可复现、可读，由条目“标题/名称/触发语”确定性派生。
        - 规范化：去除空格、符号、括号内文本，采用小写+连字符。
        - 若同一分类存在多个子项，可加后缀（例如 -1y、-2y、-main、-spouse）。

      mapping_guide:
        version: 若未标明版本则留空。
        updated_at: 若源文含“更新于…”或版本日期则提取，否则留空。
        default_language: 固定 "zh-CN"。
        aliases: 提取标题别名、简称或英文翻译；若无则 []。
        department: 默认 "BureauOfImmigration"，若源文另有明确机构可替换。
        name: 文档主标题（去除编号与附注）。
        slug: 从目录名或英文标题生成；统一小写，用连字符连接单词。
        semantic_profile.intent_id: 依据业务语义生成（如 visa.9g.employment、visa.downgrade.status_change）。
        semantic_profile.category: PROCESSING_REQUIREMENT / CERTIFICATION / VISA / IMMIGRATION_EXIT_CLEARANCE 等。
        semantic_profile.tags: 关键词数组（签证类别、部门、关键流程等）。
        service_overview: 对应模板“1. 服务概览”段落。
        applicability.items: “2. 适用情境”每条为一个 map 条目。
        preconditions.required/not_eligible: “3. 办理前提”中必备与不受理内容。
        pre_required_documents: “4. 材料清单”拆分为 mandatory / conditional。
        process.steps: “5. 服务流程”编号步骤；variants 用于特殊路径（如 “首次核发/续署”）。
        pricing.items: 按“服务 × 角色 × 年限/阶段”拆分分组；每个 details.* 对应一个收费项目。
        deliverables.items: 对应“交付物”章节，用于输出 MCC 需要的关联服务。
        kpis.processing_time: 处理时长描述。
        info_collection.*: 来自“客户信息需求”或 PDF 表单字段要求。
        acknowledgement_flags: 任何 CGAF、宣誓书、隐私告知必须写入。
        faq.qas: “常见问题”逐条映射。
        disclaimers.items: “注意事项/声明”中带有“以官方为准”等语句。
        service_related.links: 文中提及的前/后置服务（如 Annual Report、PWP）。
  rewrite_md:
    model: "gpt-5-2025-08-07"
    system_prompt: |-
      role: "PROWRITER"
      description: "你是一名政务与业务文档结构化专家，任务是理解、迁移并增强指定业务说明文档，使其完全符合统一模板结构。你的目标是：吸收 BASE_DOC、PDF_SUMMARY、PRICE_DOC、TEMPLATE 四个来源中的信息，理解后用中文重写为完整、结构化、信息充分的业务说明 Markdown。"

      (省略其余提示词内容...)
  rename_attachments:
    model: "gpt-4.1-mini"
    system_prompt: |-
      你是文档归档助手。请阅读附件全文（或图像 OCR 内容），判断其在签证/认证流程中的用途。
      若现有文件名已满足以下规范，则直接复用原文件名；否则生成符合规范的新名称。规范：
      1) 文件名仅包含 1-3 个英文单词（驼峰或首字母大写连写均可），例如 Checklist、DependentApplicationForm；
      2) 不包含业务名称/部门名称，只描述用途；
      3) 内容应反映表单/清单类型（ApplicationForm、Checklist、Certification 等）。
      示例（仅供参考）：ExtensionApplicationForm, NewApplicationForm, Checklist, DependentApplicationForm, CertificationApplication。
      命名决策优先依据以下关键词：若正文标题或开头含有 'Checklist'、'Checklist of'、'Checklist for' 等字样，输出 Checklist；若出现 'Application Form', 'Petition Form', 'Request Form' 等，输出 ApplicationForm 或更具体如 DependentApplicationForm；若为证明类包含 'Certification'、'Certificate' 等，则输出 CertificationApplication；如无法根据关键词判断，再综合文意选择最贴切的 1-3 个词。
      返回 JSON：{"filename": "..."}，值需附带扩展名（例如 Checklist.pdf）。
  update_prices:
    model: "gpt-4.1"
    system_prompt: |-
      You are BI_PRICE_EDITOR. Update the Bureau of Immigration price reference Markdown.
      - Maintain a clear Markdown structure grouped by service and fee type.
      - Update existing fees if RAW_DATA 提供不同数值（并在条目后附 "(updated YYYY-MM)"）。
      - Add new services from RAW_DATA if not in the existing document。
      - Include currency, amount, applicable notes, and links/source references where available。
      - If a fee is "以现场 OPS 为准"，将 amount.value 置空，notes 标注说明。
  fetch_visas:
    model: "gpt-4.1-mini"
    system_prompt: |-
      You are a documentation specialist. Rewrite the provided visa/service description as a structured Markdown guide with sections: Overview, Eligibility, Requirements, Process, Fees (if mentioned), Notes, References. 保持来源 URL，输出仅为 Markdown 内容。
