metadata:
  locale: en-US
  audience: internal
  version: "2025-11-01"
  notes: "Bootstrap prompts for UnifiedCS Telegram pipeline – dev phase"

agent_triage_system:
  locale: en-US
  audience: orchestration
  text: |-
    You are the triage controller for UnifiedCS, a concierge that assists with Philippine government services.
    Analyse the incoming Telegram message and prepare guidance for downstream routing.

    Incoming message:
    {user_message}

    Intent candidates to evaluate: {intent_candidates}
    Domain profiles in scope: {domain_profiles}

    Produce a concise analysis that helps the reasoning pipeline decide whether to continue, escalate, or refuse.
  variables:
    user_message:
      required: true
    intent_candidates:
      required: true
    domain_profiles:
      required: true

agent_consult_compose:
  locale: en-US
  audience: assistant
  text: |-
    Compose the next assistant turn for UnifiedCS (Philippine government service concierge).
    Maintain the specified tone: {tone}
    Stay within the token budget: {token_budget}

    Context snippets (most recent first):
    {context_snippets}

    Provide a helpful, policy-compliant reply that nudges the user toward a clear, actionable government-service question.
  variables:
    tone:
      required: true
    token_budget:
      required: true
    context_snippets:
      required: true

telegram_history_summarize:
  locale: en-US
  audience: assistant
  text: |-
    Summarise the recent Telegram history for UnifiedCS.
    Token limit for the summary: {limit_tokens}

    History excerpts:
    {history_chunks}

    Output a short bullet list capturing intent, context, and open questions that matter for the next response.
  variables:
    history_chunks:
      required: true
    limit_tokens:
      required: true

agent_refusal_policy:
  locale: en-US
  audience: assistant
  text: |-
    Inform the user that the request cannot be processed because it violates {rule}.
    Apologise briefly, restate the allowed scope (Philippine government services), and direct the user to contact {contact} if they need human help.
  variables:
    rule:
      required: true
    contact:
      required: true

telegram_prompt_missing:
  locale: en-US
  audience: assistant
  text: |-
    I’m here to help with Philippine government services. Could you describe the service, document, or procedure you need help with so I can guide you properly?
  variables: {}

webhook_signature_fail:
  locale: en-US
  audience: operator
  text: |-
    UnifiedCS could not validate the webhook signature for request {request_id}. Reject the request and log this identifier for follow-up diagnostics.
  variables:
    request_id:
      required: true

agency_compose_header:
  locale: en-US
  audience: assistant
  text: |-
    Prepare the heading for a UnifiedCS response about a Philippine government service.
    Mention the agency and the core topic succinctly so the user knows the scope immediately.
  variables:
    agency_name:
      required: false
      default: ""
    topic:
      required: false
      default: ""

agency_compose_body:
  locale: en-US
  audience: assistant
  text: |-
    Draft the detailed body for a UnifiedCS service explanation.
    Break down eligibility, required documents, submission location, and follow-up reminders in plain English.
    Keep the focus on Philippine government services and cite policies when possible.
  variables: {}

agent_plan_executor:
  locale: en-US
  audience: assistant
  text: |-
    Translate the current service plan into actionable next steps for the user.
    Highlight sequencing, dependencies, and any deadlines or agency appointments.
  variables: {}

pricing_summary:
  locale: en-US
  audience: assistant
  text: |-
    Summarise the latest pricing data we hold for the requested service.
    Call out official fees, accepted payment channels, and known surcharge scenarios.
  variables: {}

telegram_user_clarify:
  locale: en-US
  audience: assistant
  text: |-
    I want to make sure I understood your request. Could you clarify the Philippine government service or document you are working on, and tell me where you are in the process?
  variables: {}

telegram_toolcall_error:
  locale: en-US
  audience: assistant
  text: |-
    I tried to look up the requested information but the internal tool returned an error. Please wait a moment and resend your question, or specify the government service again so I can retry.
  variables: {}

telegram_welcome:
  locale: en-US
  audience: assistant
  text: |-
    Hello! I’m UnifiedCS, here to guide you through Philippine government services. Describe the permit, visa, or document you’re working on and I’ll help you figure out the next steps.
  variables: {}

budget_alert:
  locale: en-US
  audience: ops
  text: |-
    UnifiedCS hit the configured token budget threshold. Pause non-critical actions, review active conversations, and consider scaling limits.
  variables: {}

agency_pricing_alert:
  locale: en-US
  audience: ops
  text: |-
    Pricing feed for a referenced agency is missing or outdated. Trigger a pricing refresh workflow before sending cost-sensitive answers.
  variables: {}

aiogram_bootstrap_alert:
  locale: en-US
  audience: ops
  text: |-
    Aiogram bootstrap reported an error during startup. Inspect the webhook registration and environment variables immediately.
  variables: {}

aiogram_bootstrap_status:
  locale: en-US
  audience: ops
  text: |-
    Aiogram bootstrap completed successfully. Telegram handlers are ready to receive updates.
  variables: {}

asset_cleanup_summary:
  locale: en-US
  audience: ops
  text: |-
    Asset cleanup completed. Summarise which cached artifacts were removed and whether any manual follow-up is required.
  variables: {}

asset_guard_violation:
  locale: en-US
  audience: ops
  text: |-
    Guardrails flagged a prohibited asset state. Review the violation, reset the asset, and document corrective actions.
  variables: {}

kb_index_missing_agency:
  locale: en-US
  audience: ops
  text: |-
    KnowledgeBase index lookup did not contain a referenced agency. Add the agency index or adjust routing configuration.
  variables: {}

kb_index_ready:
  locale: en-US
  audience: ops
  text: |-
    KnowledgeBase index build finished and is ready for use in UnifiedCS routing.
  variables: {}

kb_pipeline_failed:
  locale: en-US
  audience: ops
  text: |-
    KnowledgeBase pipeline failed. Inspect logs, fix the underlying issue, and rerun the pipeline before users hit stale content.
  variables: {}

kb_pipeline_success:
  locale: en-US
  audience: ops
  text: |-
    KnowledgeBase pipeline succeeded. Newly ingested documents are live.
  variables: {}

memory_checksum_mismatch:
  locale: en-US
  audience: ops
  text: |-
    Memory store checksum mismatch detected. Trigger a snapshot restore or investigation before continuing sessions.
  variables: {}

memory_loader_alert:
  locale: en-US
  audience: ops
  text: |-
    Memory loader reported an operational warning. Inspect ingestion logs and confirm continuity of the conversation memory service.
  variables: {}

memory_snapshot_ready:
  locale: en-US
  audience: ops
  text: |-
    Conversation memory snapshot is ready. Archive or deploy according to the maintenance plan.
  variables: {}

plan_autodiscovery_status:
  locale: en-US
  audience: ops
  text: |-
    Autodiscovery routine for service plans finished. Review generated plans and annotate any irregularities.
  variables: {}

pricing_error:
  locale: en-US
  audience: ops
  text: |-
    A pricing computation failed. Verify the upstream rate tables and restart the pricing aggregator if needed.
  variables: {}

telegram_streaming_error:
  locale: en-US
  audience: ops
  text: |-
    Telegram streaming encountered an unexpected error. Check webhook delivery status and the aiogram worker logs.
  variables: {}

webhook_register_retry:
  locale: en-US
  audience: ops
  text: |-
    Webhook registration failed and will be retried. Monitor the retry status and verify the Telegram token configuration.
  variables: {}

core_schema_violation:
  locale: en-US
  audience: operator
  text: |-
    The inbound Telegram update failed schema validation: {error}
    Reject the payload, log the error, and escalate if the pattern repeats.
  variables:
    error:
      required: true

core_envelope_attachment:
  locale: en-US
  audience: dev
  text: |-
    Attached the raw core envelope for debugging. Review payload fidelity before shipping changes.
  variables: {}

core_envelope_gap:
  locale: en-US
  audience: dev
  text: |-
    Detected a missing field in the core envelope. Document the gap and patch the upstream generator.
  variables: {}

core_schema_alert:
  locale: en-US
  audience: dev
  text: |-
    Core schema drift detected. Update schema definitions or reconcile contract expectations immediately.
  variables: {}

entry_layout_violation:
  locale: en-US
  audience: dev
  text: |-
    An entry layout violated repository conventions. Cross-check WorkPlan guidelines and repair the layout.
  variables: {}

entry_missing_file:
  locale: en-US
  audience: dev
  text: |-
    A required file is missing from the entry bundle. Restore the file or update manifests before deployment.
  variables: {}

kb_routing_conflict:
  locale: en-US
  audience: dev
  text: |-
    KnowledgeBase routing produced conflicting agency matches. Resolve the overlap to prevent misdirected answers.
  variables: {}

layout_missing_dir:
  locale: en-US
  audience: dev
  text: |-
    Expected directory absent in layout scaffolding. Create the directory to satisfy WorkPlan constraints.
  variables: {}

layout_owner_mismatch:
  locale: en-US
  audience: dev
  text: |-
    Directory ownership labels mismatch WorkPlan annotations. Align metadata before publishing artifacts.
  variables: {}

plan_alignment_gap:
  locale: en-US
  audience: dev
  text: |-
    Detected a gap between documented plan and implementation. Record the delta and schedule remediation.
  variables: {}

plan_scope_ack:
  locale: en-US
  audience: dev
  text: |-
    Scope acknowledgement recorded. Continue execution but notify stakeholders if boundaries change.
  variables: {}

selector_match_debug:
  locale: en-US
  audience: dev
  text: |-
    Selector debug information: verify the matcher logic and keep this entry for audit trails.
  variables: {}

slot_missing:
  locale: en-US
  audience: dev
  text: |-
    A required slot is missing in the pipeline configuration. Fill the slot or update the schema.
  variables: {}

slot_validation_error:
  locale: en-US
  audience: dev
  text: |-
    Slot validation failed. Inspect slot definitions and adjust field mappings accordingly.
  variables: {}
